### ISSUE TITLE
Xamarin Error CS0029

### ISSUE THREAD

**Issue by nathandaniels** [davetimmins/ArcGIS.PCL.XamarinMaps#2]
The line:
List<Pin> pins = ViewModel.LoadPins();
in MapPage.cs I get the following error:

Cannot implicitly convert type `System.Threading.Tasks.Task<System.Collections.Generic.List<Xamarin.Forms.Maps.Pin>>' to`System.Collections.Generic.List<Xamarin.Forms.Maps.Pin>' (CS0029)

Any ideas why this may be occurring? Any advice is appreciated. I have copied and pasted code from the 'Using ArcGIS Server with Xamarin Forms Maps blog' into the MapViewModel.cs. I have also added the using statements. In MapViewModel.cs the line:
public async Task<List<Pin>> LoadPins()
has been inserted directly under the '}' which closes off the public MapViewModel()

**Comment by davetimmins** [comment]
The error is due to the `LoadPins` now being async so ideally the calling context would also be async but in the MobileCRM project it is set to load in the constructor so I just changed the `ViewModel.LoadPins();` to be `ViewModel.LoadPins().Result;`

**Comment by davetimmins** [comment]
Another way around the issue that will avoid a potential deadlock is to load the pins from an event. There are already events for the menu buttons so in the MapPage.cs file you can change the initial loading

``` c#
public Map MakeMap()
{
    List<Pin> pins = new List<Pin>(); // ViewModel.LoadPins();
```

and then add the loading to one of the events, e.g. when you click the search icon

``` c#
searchAddress.SearchButtonPressed += async (e, a) =>
{
    var pins = await ViewModel.LoadPins();
    foreach (var p in pins.Item2)
    {
        map.Pins.Add(p);
    }
```
